version: '3.4'
services:
  dbrw:
    image: mysql:5.7.24
    volumes:
      - tasks_api_db:/var/lib/mysql
    environment:
      MYSQL_USER: tasks_api
      MYSQL_PASSWORD: apitasks
      MYSQL_DATABASE: tasks_api
      MYSQL_ROOT_PASSWORD: superPassWoRd

  api:
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - dbrw
    ports:
      - 3000:8000
    command: cargo run

volumes:
  tasks_api_db:
    driver: local
